services:
  - type: web
    name: Cms-my
    runtime: docker
    plan: starter
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: APP_ENV
        value: production
      - key: SESSION_HTTPS_ONLY
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: CMS_FILE_LOGGING
        value: "true"
