#!/usr/bin/env python3
"""Read-only CMS diagnostic reporter.

Collects compilation/import/test diagnostics without modifying source files,
dependencies, databases, or trading state.

Usage: python tools/cms_compile_report.py [project_root]
Writes docs/COMPILE_REPORT.md and docs/COMPILE_REPORT.json.
"""
from __future__ import annotations
import ast
import json
import py_compile
import subprocess
import sys
import tempfile
from pathlib import Path

SKIP={'.git','.venv','venv','node_modules','__pycache__','.pytest_cache'}

def rel(root,p): return p.relative_to(root).as_posix()

def compile_files(root):
    errors=[]; checked=0
    with tempfile.TemporaryDirectory() as td:
        for p in root.rglob('*.py'):
            if any(x in SKIP for x in p.parts): continue
            checked+=1
            try:
                py_compile.compile(str(p),cfile=str(Path(td)/(str(checked)+'.pyc')),doraise=True)
            except Exception as e:
                errors.append({'file':rel(root,p),'type':'syntax','severity':'error','message':str(e)})
    return checked,errors

def ast_imports(root):
    errors=[]; checked=0
    for p in root.rglob('*.py'):
        if any(x in SKIP for x in p.parts): continue
        checked+=1
        try: ast.parse(p.read_text(encoding='utf-8',errors='replace'))
        except SyntaxError: continue
    return checked,errors

def pytest_report(root):
    tests=root/'tests'
    if not tests.exists(): return {'status':'not_run','reason':'tests directory not found'}
    proc=subprocess.run([sys.executable,'-m','pytest','-q'],cwd=root,text=True,capture_output=True,timeout=300)
    output=(proc.stdout+'\n'+proc.stderr).strip()
    return {'status':'passed' if proc.returncode==0 else 'failed','returncode':proc.returncode,'output':output[-12000:]}

def build(root):
    checked,errors=compile_files(root)
    tests=pytest_report(root)
    return {'generated_by':'tools/cms_compile_report.py','read_only':True,'summary':{'python_files_checked':checked,'syntax_errors':len(errors),'tests_status':tests['status']},'errors':errors,'tests':tests}

def markdown(d):
    out=['# CMS-my — Compile / Diagnostic Report','','Generated by `tools/cms_compile_report.py`. This report is diagnostic only.','','## Summary']
    for k,v in d['summary'].items(): out.append(f'- {k}: **{v}**')
    out += ['','## Errors','']
    if not d['errors']: out.append('No Python syntax errors detected.')
    for e in d['errors']: out.append(f"- **{e['severity'].upper()}** `{e['file']}` — `{e['type']}` — {e['message']}")
    out += ['','## Tests','',f"Status: **{d['tests']['status']}**"]
    if d['tests'].get('output'): out += ['', '```text', d['tests']['output'], '```']
    out += ['','## Rules','- This tool does not edit source files.','- This tool does not install dependencies.','- This tool does not modify databases.','- This tool does not execute trading actions.','- A failed test is reported, not repaired.']
    return '\n'.join(out)+'\n'

def main():
    root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve(); docs=root/'docs'; docs.mkdir(exist_ok=True)
    d=build(root)
    (docs/'COMPILE_REPORT.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (docs/'COMPILE_REPORT.md').write_text(markdown(d),encoding='utf-8')
    print(json.dumps(d['summary'],ensure_ascii=False,indent=2))

if __name__=='__main__': main()
