#!/usr/bin/env python3
"""Static CMS request/path mapper. Read-only; does not execute the app.

Usage: python tools/cms_request_mapper.py [project_root]
Writes docs/REQUEST_MAP.md and docs/REQUEST_MAP.json.
"""
from __future__ import annotations
import ast
import json
import re
import sys
from pathlib import Path

SKIP={'.git','.venv','venv','node_modules','__pycache__','.pytest_cache'}
ROUTE={'get','post','put','patch','delete','options','head','route'}
PRIVATE={'create_order','cancel_order','edit_order','fetch_balance','fetch_orders','fetch_open_orders','fetch_closed_orders','fetch_my_trades','fetch_positions','api_key','api_secret','api_password'}
PUBLIC={'fetch_ticker','fetch_order_book','fetch_ohlcv','fetch_trades'}
DB={'SessionLocal','create_engine','sqlite','session.query','session.add','session.commit'}
URL_RE=re.compile(r"[\"'`]((?:/api|/login|/register|/dashboard|/settings|/marketplace|/bot-management|/admin|/wallet|/install|/logout)[^\"'` ]*)")
WS_RE=re.compile(r"(?:new WebSocket|WebSocket\()\s*\(\s*[`\"']([^`\"']+)")

def rel(root,p): return p.relative_to(root).as_posix()
def literal(n):
    try:
        v=ast.literal_eval(n); return v if isinstance(v,str) else None
    except Exception: return None

def flags(text):
    lo=text.lower()
    return {'private_exchange':any(x.lower() in lo for x in PRIVATE),'public_market_data':any(x.lower() in lo for x in PUBLIC),'database':any(x.lower() in lo for x in DB)}

def routes_from(root):
    routes=[]; sensitive=[]; modules=[]
    for p in root.rglob('*.py'):
        if any(x in SKIP for x in p.parts): continue
        src=p.read_text(encoding='utf-8',errors='replace'); f=flags(src)
        modules.append({'file':rel(root,p),**f})
        try: tree=ast.parse(src)
        except SyntaxError as e:
            sensitive.append({'file':rel(root,p),'kind':'syntax_error','detail':str(e)}); continue
        for n in ast.walk(tree):
            if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)):
                for d in n.decorator_list:
                    if not isinstance(d,ast.Call): continue
                    name=d.func.attr if isinstance(d.func,ast.Attribute) else d.func.id if isinstance(d.func,ast.Name) else ''
                    if name not in ROUTE: continue
                    path=literal(d.args[0]) if d.args else '<dynamic>'
                    methods=[name.upper()]
                    if name=='route':
                        for kw in d.keywords:
                            if kw.arg=='methods':
                                try: methods=[str(x).upper() for x in ast.literal_eval(kw.value)]
                                except Exception: pass
                    routes.append({'file':rel(root,p),'path':path or '<dynamic>','methods':methods,'handler':n.name,**f})
        for i,line in enumerate(src.splitlines(),1):
            lf=flags(line)
            if lf['private_exchange'] or lf['public_market_data']:
                sensitive.append({'file':rel(root,p),'line':i,'text':line.strip()[:240],**lf})
    return routes,sensitive,modules

def web_refs(root):
    refs=[]; sockets=[]; templates=[]
    for p in root.rglob('*'):
        if p.suffix not in {'.html','.js','.ts','.tsx','.jsx'} or any(x in SKIP for x in p.parts): continue
        src=p.read_text(encoding='utf-8',errors='replace')
        for m in URL_RE.finditer(src): refs.append({'file':rel(root,p),'url':m.group(1)})
        for m in WS_RE.finditer(src): sockets.append({'file':rel(root,p),'url':m.group(1)})
        if p.suffix=='.html':
            for m in re.finditer(r"url_for\(\s*['\"]([^'\"]+)",src): templates.append({'file':rel(root,p),'endpoint':m.group(1)})
    return refs,sockets,templates

def build(root):
    r,s,m=routes_from(root); w,ws,t=web_refs(root)
    return {'generated_by':'tools/cms_request_mapper.py','routes':sorted(r,key=lambda x:(x['path'],x['file'])),'frontend_requests':w,'websockets':ws,'template_endpoints':t,'sensitive_calls':s,'modules':m,'summary':{'routes':len(r),'frontend_requests':len(w),'websockets':len(ws),'template_refs':len(t),'private_files':sum(x['private_exchange'] for x in m),'public_market_files':sum(x['public_market_data'] for x in m),'db_files':sum(x['database'] for x in m)}}

def markdown(d):
    out=['# CMS-my — Request / Path Map','','Generated by `tools/cms_request_mapper.py`. Static analysis only.','Run before major audits to detect route/request drift.','','## Summary']
    for k,v in d['summary'].items(): out.append(f'- {k}: **{v}**')
    out += ['','## Backend routes','','| Method | Path | Handler | File | Private | Market | DB |','|---|---|---|---|---:|---:|---:|']
    for x in d['routes']:
        y=lambda k:'YES' if x[k] else '—'
        out.append(f"| {', '.join(x['methods'])} | `{x['path']}` | `{x['handler']}` | `{x['file']}` | {y('private_exchange')} | {y('public_market_data')} | {y('database')} |")
    out += ['','## Frontend requests','']
    out += [f"- `{x['file']}` → `{x['url']}`" for x in d['frontend_requests']]
    out += ['','## WebSockets','']
    out += [f"- `{x['file']}` → `{x['url']}`" for x in d['websockets']]
    out += ['','## Template endpoint references','']
    out += [f"- `{x['file']}` → `{x['endpoint']}`" for x in d['template_endpoints']]
    out += ['','## Sensitive exchange locations','']
    out += [f"- `{x['file']}:{x.get('line','?')}` — `{x.get('text','')}`" for x in d['sensitive_calls'] if x.get('private_exchange')]
    out += ['','## Audit rules','1. Backend route without frontend reference: inspect for legacy/unused API.','2. Frontend request without backend route: broken-function candidate.','3. Private exchange call outside execution guard: security blocker.','4. Public market-data path using credentials: credential-exposure candidate.','5. Duplicate routes: investigate before deleting.']
    return '\n'.join(out)+'\n'

def main():
    root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve(); d=build(root); docs=root/'docs'; docs.mkdir(exist_ok=True)
    (docs/'REQUEST_MAP.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    (docs/'REQUEST_MAP.md').write_text(markdown(d),encoding='utf-8')
    print(json.dumps(d['summary'],ensure_ascii=False,indent=2))
if __name__=='__main__': main()
